'use client';

import React from 'react';
import Link from 'next/link';

export default function TermsPage() {
  return (
    <div style={{
      minHeight: '100vh',
      background: 'radial-gradient(circle at top left, #0e121e 0%, #08090c 70%)',
      color: '#f8f9fa',
      padding: '80px 24px 120px 24px',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center'
    }}>
      <div style={{ maxWidth: '800px', width: '100%', display: 'flex', flexDirection: 'column', gap: '32px' }}>
        {/* Back Link */}
        <div>
          <Link href="/" style={{
            color: '#4F8CFF',
            textDecoration: 'none',
            fontSize: '14px',
            fontWeight: 600,
            display: 'inline-flex',
            alignItems: 'center',
            gap: '8px'
          }}>
            ← Back to Home
          </Link>
        </div>

        {/* Header */}
        <div>
          <h1 style={{
            fontSize: '40px',
            fontWeight: 900,
            background: 'linear-gradient(135deg, #ffffff 30%, #a5b4fc 100%)',
            WebkitBackgroundClip: 'text',
            WebkitTextFillColor: 'transparent',
            margin: '0 0 12px 0',
            letterSpacing: '-0.03em'
          }}>
            Terms of Service
          </h1>
          <p style={{ color: '#75777F', fontSize: '15px', lineHeight: '24px', margin: 0 }}>
            Read the terms and conditions for using our automated AutoML platform.
          </p>
        </div>

        {/* Content Panel */}
        <div style={{
          background: 'rgba(255, 255, 255, 0.03)',
          border: '1px solid rgba(255, 255, 255, 0.08)',
          borderRadius: '16px',
          padding: '40px',
          backdropFilter: 'blur(16px)',
          display: 'flex',
          flexDirection: 'column',
          gap: '32px'
        }}>
          {/* Section 1 */}
          <section>
            <h2 style={{ fontSize: '20px', fontWeight: 700, margin: '0 0 12px 0', color: '#ffffff' }}>1. Service Agreement</h2>
            <p style={{ color: '#abb2bf', fontSize: '14px', lineHeight: '24px', margin: 0 }}>
              OptiAgent.ML provides an automated artificial intelligence agent to pre-process, train, optimize, and serialize machine learning models. By uploading datasets, you agree that you possess the necessary authorization to process the records.
            </p>
          </section>

          {/* Section 2 */}
          <section style={{ borderTop: '1px solid rgba(255, 255, 255, 0.08)', paddingTop: '24px' }}>
            <h2 style={{ fontSize: '20px', fontWeight: 700, margin: '0 0 12px 0', color: '#ffffff' }}>2. Fair Usage Policy</h2>
            <p style={{ color: '#abb2bf', fontSize: '14px', lineHeight: '24px', margin: 0 }}>
              To ensure platform resource availability, our sandbox executors enforce strict execution constraints. Uploads of malicious files, executable scripts, or queries designed to bypass python sandboxes are strictly prohibited and will result in account suspension.
            </p>
          </section>

          {/* Section 3 */}
          <section style={{ borderTop: '1px solid rgba(255, 255, 255, 0.08)', paddingTop: '24px' }}>
            <h2 style={{ fontSize: '20px', fontWeight: 700, margin: '0 0 12px 0', color: '#ffffff' }}>3. Disclaimer of Liability</h2>
            <p style={{ color: '#abb2bf', fontSize: '14px', lineHeight: '24px', margin: 0 }}>
              Predictions and accuracies generated by the agent depend on the user-supplied dataset. OptiAgent.ML is provided "as is" without guarantees of production readiness or specific performance targets.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
